apiVersion: v1
kind: Template
metadata:
  name: deploymentconfiguration-template
parameters:
- name: APPLICATION_NAME
- name: SHARED_FILE_PATH
- name: SPRING_PROFILE
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            name: '${APPLICATION_NAME}:dev'
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            image: ${APPLICATION_NAME}:dev
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: spring.config.additional-location
                value: ${SHARED_FILE_PATH}/db.properties
            envFrom:
              - configMapRef:
                  name: shared-configurations
            resources: {}
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: ${SHARED_FILE_PATH}
              name: dbproperties
              readOnly: true
        restartPolicy: Always
        volumes:
        - name: dbproperties
          secret:
            defaultMode: 420
            secretName: database-connection-secret
